spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=nyilvantarto;encrypt=true;trustServerCertificate=true
    username: sa
    password: PassWord_1234
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: on
